### ISSUE TITLE
use theme color, instead of forcing to black

### ISSUE THREAD

**Issue by killarny** [rockon999/dynamic-panel-transparency#2]
When a window is maximized, this extension seems to be "forcing" the top bar to be black, rather than using the color that my theme is defining.

**Comment by rockon999** [comment]
This is sadly by design. To achieve the fade effect I have to strip the panel's color theming. Until I can find a reliable method of retrieving the user's theme colors it will have to stay the default black. *This is currently my top priority though!* Even if I'm unable to do this automatically, I'll be adding a manual color setting to the extension in the next release.

**Comment by msx** [comment]
Rock on this feature!

**Comment by coderstephen** [comment]
Yes please! At least a setting to choose what RGB color to fade from. For now, if you want to tweak the colors, you can edit `extension.js` and replace 0s with the RGB value of your choice.

**Comment by rockon999** [comment]
The newest git has color and opacity settings! I won't be releasing it to gnome.org until I've fully tested this version.

**Comment by rockon999** [comment]
The newest git can now detect the user's theme based on their original panel and dash coloring!
