### ISSUE TITLE
Add setting to enable always-on transparency

### ISSUE THREAD

**Issue by Krishath** [rockon999/dynamic-panel-transparency#33]
It would be great to have the bar transparent at all times!

**Comment by rockon999** [comment]
If you want the bar to always be transparent set both the maximum and minimum opacities to 0. If I misunderstood your request feel free to elaborate!

As an aside, I don't recommend my extension for this behavior because it runs logic to detect when windows maximize/minimize and adjusts the transparency accordingly. If you want a constant transparency (one that doesn't change when windows are maximized)... I'd use [Activities Configurator](https://extensions.gnome.org/extension/358/activities-configurator/).

**Comment by Krishath** [comment]
I'm sorry. You're right! I totally missed that option! GREAT extension!
