### ISSUE TITLE
Panel animation is not triggered when using "Hide all normal windows" feature of gnome

### ISSUE THREAD

**Issue by hydbird** [rockon999/dynamic-panel-transparency#61]
There is a keyboard shortcut in gnome-settings/keyboard called "Hide all normal windows". When using this feature, the panel animation is not triggered even though all windows are hidded.

Gnome Version 3.22.2

**Comment by rockon999** [comment]
Do you have desktop icons enabled?

**Comment by hydbird** [comment]
No

**Comment by rockon999** [comment]
Issue #46 dealt with this. The problem with that shortcut is its implementation is quite backwards. Right now the extension will update only if desktop icons are enabled as I haven't found a reliable way to detect it otherwise. My previous logic was that very few users would be showing an empty desktop. Could you describe your use case?

**Comment by hydbird** [comment]
The thing is I've a conky window on my desktop so I often hide windows to look at that info. Or if I'm working with multiple windows but my workflow is interrupted I hide all the windows and focus on that interruption. I didn't see the issue #46  sorry about that.

**Comment by rockon999** [comment]
Ah, I hadn't thought of that use case. I'll see what I can do to better handle this shortcut.

**Comment by hydbird** [comment]
Thanks, good luck.

**Comment by rockon999** [comment]
As a workaround you can go into Tweak Tool, enable desktop icons, and then remove anything on the desktop.

**Comment by rockon999** [comment]
@ksthiele If you could please try the latest from the GitHub, I think I may have found a solution to this issue. Thanks :)
