### ISSUE TITLE
Transition between Desktop and Activities Overview

### ISSUE THREAD

**Issue by Gomme-** [rockon999/dynamic-panel-transparency#69]
Hi. First, great extension! 

Now, this is not a bug, more a remark for a possible aesthetic improvement from a common user :
The fading of opacity and change of colour of the text when passing from the desktop to the activities overview (or the other way) happen AFTER the animation of gnome, that could be smoother if they  could happen before or at the same time. 

For example, I have right now black colour for the text in the desktop and white in overview. So the transition goes : I am in the desktop view so black text then if i hit the overview the usual gnome animation happens and darken the screen and once it finishes the font suddenly turn white. (Tested on a live session of ubuntu gnome 17.04 everything untouched and just the extension installed.) 
(The same thing happens with the colour of the bar when passing from desktop with a maximize window to the overview and the other way)

I hope that you understand this remark (and my English).

**Comment by rockon999** [comment]
I understand you perfectly! This issue has been brought up before. See #52. Currently the main reason I keep it after is because it causes significant lag on some systems if I run the extension code while the shell is transitioning. To address this, I will be adding a setting the lets the user decide when to run the transition.

**Comment by rockon999** [comment]
A setting has been added in v21/v22. Fix pending review on Gnome Extensions.
